spring:
  application:
    name: eureka-hystrix
server:
  port: 1007
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

# feign断路器，默认关闭
feign:
  hystrix:
    enabled: true