spring:
  application:
    name: stream-rabbitmq
  # rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # bus 配置
#  cloud:
#    bus:
#      ack:
#        enabled: true
#        trace:
#          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 1020
