spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oubin17/springcloud/
          search-paths: src/main/resources
      label: master
server:
  port: 1010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
